- id: '1622706168523'
  alias: Long Press on Entry Switch -> Turn On Lights
  description: ''
  trigger:
  - device_id: 64185ca2086c2ebd7b976a43ef0c89fd
    domain: hue
    platform: device
    type: repeat
    subtype: 1
    unique_id: c1c9f277-e27a-4340-9962-2206cc0d7e3a
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.reset_lights_day_area
    data: {}
  mode: single
- id: '1622706310024'
  alias: Long Press on Entry Switch -> Get Out
  description: ''
  trigger:
  - device_id: 64185ca2086c2ebd7b976a43ef0c89fd
    domain: hue
    platform: device
    type: repeat
    subtype: 4
    unique_id: 7564eab9-3cc9-4321-890c-1b9f1465f108
  condition: []
  action:
  - service: script.turn_on
    target:
      entity_id: script.leave_home
    data: {}
  mode: single
