# DEFAULT

default_config:

api:

# COMPONENTS
sensor: !include components/sensor.yaml
binary_sensor: !include components/binary_sensor.yaml
proximity: !include components/proximity.yaml


# INPUTS
input_boolean: !include inputs/input_boolean.yaml
input_datetime: !include inputs/input_datetime.yaml

# MISC
http: !include misc/http.yaml
recorder: !include misc/recorder.yaml
    
# AUTOMATIONS
automation: !include automations.yaml

# SCRIPTS
script: !include scripts.yaml


