# https://www.home-assistant.io/integrations/binary_sensor/

# Workday (current day)
# https://www.home-assistant.io/integrations/workday/
- platform: workday
  name: 'workday_today' 
  country: FR

# Workday (Tomorrow)
# https://www.home-assistant.io/integrations/workday/
- platform: workday
  name: 'workday_tomorrow' 
  country: FR
  days_offset: 1
  
# Home Occupancy
# https://www.home-assistant.io/integrations/binary_sensor.template/
- platform: template
  sensors:
      home_occupied:
          friendly_name: "Maison"
          device_class: occupancy
          value_template: "{{is_state('person.jenova70', 'home') or is_state('person.valentine', 'home')}}"
          icon_template: >
              {% if is_state("binary_sensor.home_occupied", "on") -%}
                  mdi:home-account
              {%- else -%}
                  mdi:home
              {%- endif %}


# TV usage
# https://www.home-assistant.io/integrations/binary_sensor.template/
- platform: template
  sensors:
      is_tv_used:
          value_template: "{{is_state('media_player.philips_android_tv', 'playing') or is_state('media_player.philips_android_tv', 'paused')}}"

# PS5 Usage
# https://www.home-assistant.io/integrations/binary_sensor.template/
- platform: template
  sensors:
      is_ps5_used:
          value_template: "{{is_state_attr('media_player.philips_android_tv', 'hdmi_input', 'HW5')}}"

# Sun rising
# https://www.home-assistant.io/integrations/binary_sensor.template/
- platform: template
  sensors:
      is_sun_rising:
          value_template: "{{is_state_attr('sun.sun', 'rising', true)}}"