# https://www.home-assistant.io/integrations/binary_sensor/

# Workday (current day)
# https://www.home-assistant.io/integrations/workday/
- platform: workday
  name: 'workday_today' 
  country: FR

# Workday (Tomorrow)
# https://www.home-assistant.io/integrations/workday/
- platform: workday
  name: 'workday_tomorrow' 
  country: FR
  days_offset: 1