# Nmap device tracker (Used for presence detection)
#https://www.home-assistant.io/integrations/nmap_tracker/
- platform: nmap_tracker
  hosts: 
    - 192.168.1.34
    - 192.168.1.18
    - 192.168.1.14
  interval_seconds: 30
  consider_home: 300
  home_interval: 3
