# Group composed of all the ceiling lights of the kitchen
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "kitchen_ceiling"
  entities:
    - light.kitchen_ceiling_a
    - light.kitchen_ceiling_b
    - light.kitchen_ceiling_c
    
    

# Group composed of all the wall lights of living room
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "living_room_wall"
  entities:
    - light.living_room_wall_a
    - light.living_room_wall_b
    

# Group composed of all the ceiling lights of main bed room
# https://www.home-assistant.io/integrations/light.group/    
- platform: group
  name: "main_bedroom_ceiling"
  entities:
    - light.main_bedroom_ceiling_a
    - light.main_bedroom_ceiling_b

# Group composed of all the interior lights
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "interior_lights"
  entities:
    - light.cuisine
    - light.salon
    - light.entree
    - light.chambre_principale
    - light.chambre_secondaire
    
# Group composed of all the exterior lights
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "exterior_lights"
  entities:
    - light.terrasse


      