# Group composed of all the ceiling lights of the kitchen
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "kitchen_ceiling"
  entities:
    - light.cuisine_suspension_a
    - light.cuisine_suspension_b
    - light.cuisine_suspension_c
    
    

# Group composed of all the wall lights of living room
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "living_room_wall"
  entities:
    - light.salon_applique_a
    - light.salon_applique_b
    

# Group composed of all the ceiling lights of main bed room
# https://www.home-assistant.io/integrations/light.group/    
- platform: group
  name: "main_bedroom_ceiling"
  entities:
    - light.chambre_suspension_blanche
    - light.chambre_suspension_jaune

# Group composed of all the lights of the living area
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "living_lights"
  entities:
    - light.cuisine
    - light.salon
    - light.entree
    
# Group composed of all the interior lights
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "interior_lights"
  entities:
    - light.cuisine
    - light.salon
    - light.entree
    - light.chambre_principale
    - light.chambre_secondaire
    
# Group composed of all the exterior lights
# https://www.home-assistant.io/integrations/light.group/
- platform: group
  name: "exterior_lights"
  entities:
    - light.terrasse


