# ANDROID TV
# https://www.home-assistant.io/integrations/androidtv/
- platform: androidtv
  name: Philips Android TV
  device_class: androidtv
  host: 192.168.1.101
  get_sources: false
  apps:
    com.spotify.tv.android: Spotify
    org.xbmc.kodi: Kodi
    tv.molotov.app: Molotov
    com.google.android.youtube.tv: YouTube
    com.google.android.apps.mediashell: Cast
    com.google.android.tvlauncher: Home
    com.android.vending: Google Play Store
    com.amazon.amazonvideo.livingroom: Amazon Prime