# https://www.home-assistant.io/integrations/time_date/
- platform: time_date
  display_options:
    - 'date_time_iso'

# System monitoring 
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: processor_temperature

# Neato specific sensors
# https://www.home-assistant.io/integrations/template/
- platform: template
  sensors:
      # Last cleaned area (m2)
      spiroo_last_cleaning_area:
          value_template: "{{state_attr('vacuum.spiroo' , 'clean_area') | round(0) }}"
          unit_of_measurement: "m2"
          icon_template: "mdi:checkbox-blank-outline"

      # Progress of cleaning (%)
      spiroo_cleaning_progress:
          value_template: >-
            {% if is_state('vacuum.spiroo', 'cleaning') -%}
            {% set a = 100 / (state_attr("vacuum.spiroo", "battery_level_at_clean_end") | int - 100)%}
            {% set b = 10000 / ( 100 - (state_attr("vacuum.spiroo", "battery_level_at_clean_end") | int )) %}
            {% set list = (a * state_attr("vacuum.spiroo", "battery_level") | int + b) | round , 100 %}
            {{list | min}}
            {% else -%}
            100
            {%- endif %}
          icon_template: "mdi:progress-clock"
          unit_of_measurement: "%"
          


